version: "3.8"

services:
  api:
    image: kldevops/api-plantas:latest
    container_name: api-plants
    ports:
      - "8100:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: mysql-plants
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3308:3306"
    volumes:
      - /db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-plants
    restart: always
    ports:
      - "8101:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:

